[[pages]]
path = "filters.py"
name = "Streamlit-Vizzu"
icon = "ğŸ "

[[pages]]
path = "1-tutorial.py"
name = "Tutorial Example"
icon = "ğŸ“š"

[[pages]]
path = "pages/3-drilldown.py"
name = "Drilldown"
icon = "ğŸ”"

[[pages]]
path = "pages/5-complex_explorer.py"
name = "Complex Explorer"
icon = "ğŸ—ºï¸"