[[pages]]
path = "filters.py"
name = "Streamlit-Vizzu"
icon = "ğŸ "

[[pages]]
path = "pages/filters_flipped.py"
name = "Filters Flipped"
icon = "ğŸ™ƒ"

[[pages]]
path = "pages/tutorial.py"
name = "Tutorial Example"
icon = "ğŸ“š"

[[pages]]
path = "pages/drilldown.py"
name = "Drilldown"
icon = "ğŸ”"